version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-208-118.compute-1.amazonaws.com
            port: '5432'
            database: dd2detko7on8e5
            ssl: true
            user: mdhxjkgacrkijr
            password: 15020c697d776f976da0651fac51a4609e1b5c039f2a93b52bb8e35370556bbb
            migrations: true
